ALTER TABLE properties RENAME weight TO atomic_mass;
ALTER TABLE properties RENAME melting_point TO melting_point_celsius;
ALTER TABLE properties RENAME boiling_point TO boiling_point_celsius;
ALTER TABLE properties ALTER melting_point_celsius SET NOT NULL;
ALTER TABLE properties ALTER boiling_point_celsius SET NOT NULL;
ALTER TABLE properties ADD FOREIGN KEY (atomic_number) REFERENCES elements(atomic_number);
ALTER TABLE properties ADD COLUMN type_id INT REFERENCES types (type_id);
UPDATE properties SET type_id=1 WHERE type='metal';
UPDATE properties SET type_id=2 WHERE type='metalloid';
UPDATE properties SET type_id=3 WHERE type='nonmetal';
ALTER TABLE properties ALTER type_id SET NOT NULL;
ALTER TABLE properties DROP COLUMN type;
ALTER TABLE properties ALTER atomic_mass TYPE DECIMAL;
UPDATE properties SET atomic_mass=TRIM(TRAILING '0' FROM atomic_mass::TEXT)::DECIMAL;
DELETE FROM properties WHERE atomic_number < 1 OR atomic_number > 118;
ALTER TABLE elements ADD CONSTRAINT symbol UNIQUE (symbol);
ALTER TABLE elements ADD CONSTRAINT name UNIQUE (name);
ALTER TABLE elements ALTER symbol SET NOT NULL;
ALTER TABLE elements ALTER name SET NOT NULL;
UPDATE elements SET symbol=INITCAP(symbol);
DELETE FROM elements WHERE atomic_number < 1 OR atomic_number > 118;
INSERT INTO elements (atomic_number, symbol, name) VALUES (9, 'F', 'Fluorine');
INSERT INTO elements (atomic_number, symbol, name) VALUES (10, 'Ne', 'Neon');
INSERT INTO properties (atomic_number, atomic_mass, melting_point_celsius, boiling_point_celsius, type_id) VALUES (9, 18.998, -220, -188.1, 3);
INSERT INTO properties (atomic_number, atomic_mass, melting_point_celsius, boiling_point_celsius, type_id) VALUES (10, 20.18, -248.6, -246.1, 3);